// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

/*
Package indexing is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	IndexStorage
*/
package indexing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexStorage struct {
	Records []*IndexStorageRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *IndexStorage) Reset()                    { *m = IndexStorage{} }
func (m *IndexStorage) String() string            { return proto.CompactTextString(m) }
func (*IndexStorage) ProtoMessage()               {}
func (*IndexStorage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IndexStorage) GetRecords() []*IndexStorageRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type IndexStorageRecord struct {
	Key   string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
}

func (m *IndexStorageRecord) Reset()                    { *m = IndexStorageRecord{} }
func (m *IndexStorageRecord) String() string            { return proto.CompactTextString(m) }
func (*IndexStorageRecord) ProtoMessage()               {}
func (*IndexStorageRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *IndexStorageRecord) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IndexStorageRecord) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexStorage)(nil), "indexing.IndexStorage")
	proto.RegisterType((*IndexStorageRecord)(nil), "indexing.IndexStorage.record")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0xc9, 0x2f,
	0x4a, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x4b, 0x49, 0xad,
	0xc8, 0xcc, 0x4b, 0x57, 0xaa, 0xe4, 0xe2, 0xf1, 0x04, 0xb1, 0x83, 0x21, 0xf2, 0x42, 0xe6, 0x5c,
	0xec, 0x45, 0xa9, 0xc9, 0xf9, 0x45, 0x29, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xb2,
	0x7a, 0x30, 0xb5, 0x7a, 0xc8, 0x0a, 0xf5, 0x20, 0xaa, 0x82, 0x60, 0xaa, 0xa5, 0x0c, 0xb8, 0xd8,
	0x20, 0x4c, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x49, 0x81, 0x59, 0x83,
	0x33, 0x08, 0xc2, 0x49, 0x62, 0x03, 0xbb, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x50, 0xed,
	0x55, 0x8b, 0x9c, 0x00, 0x00, 0x00,
}
